version = 0.1
[default.deploy.parameters]
stack_name = "backops"
resolve_s3 = false
s3_prefix = "backops"
region = "ap-south-1"
capabilities = ['CAPABILITY_IAM', 'CAPABILITY_AUTO_EXPAND']
image_repositories = []
s3_bucket="aws-sam-cli-managed-default-samclisourcebucket-w8dj7btx59k2"
