AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: backop-backend

Resources:
  # S3 Stack
  S3Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3.yml

  # Cognito Stack
  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito.yml

  DatabaseStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: database.yml

  # API Gateway Stack
  ApiLambdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: api-lambda.yml
      Parameters:
        UserPool: !GetAtt CognitoStack.Outputs.UserPool
        UserPoolClient: !GetAtt CognitoStack.Outputs.UserPoolClient
        UploadBucket: !GetAtt S3Stack.Outputs.UploadBucket
        DynamoDBTable: !GetAtt DatabaseStack.Outputs.DynamoDBTable
